#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

setxkbmap se
picom --backend glx &
pipewire &
xrandr --output DP-4 --rotate left --right-of DP-0
feh --bg-scale ~/Pictures/wallpaper.jpg &
# Activate dbus variables
#
dbus-update-activation-environment --all
dbus-launch ssh-agent dwm
